//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBRPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInformation
    {
        public string ID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string DockitFooter { get; set; }
        public string LicenseNumber { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string DeliveryNumbers { get; set; }
        public string StoreID { get; set; }
        public string NTNNumber { get; set; }
    }
}
