//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBRPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealSetup
    {
        public string ID { get; set; }
        public string DealDescription { get; set; }
        public string DealRule { get; set; }
        public Nullable<int> IsActive { get; set; }
    }
}
