//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBRPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountSetup
    {
        public string DiscountCode { get; set; }
        public string DiscountDescription { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public string IsPercentage { get; set; }
    }
}
