//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBRPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInformation
    {
        public string EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public string FatherName { get; set; }
        public string NICNumber { get; set; }
        public string EmployeeType { get; set; }
        public string ContactNumber { get; set; }
        public string Address { get; set; }
        public byte[] EmployeePicture { get; set; }
    }
}
