//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBRPOS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POSDatabase2005Entities : DbContext
    {
        public POSDatabase2005Entities()
            : base("name=POSDatabase2005Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<CatagorySetup> CatagorySetups { get; set; }
        public virtual DbSet<CompanyInformation> CompanyInformations { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<DealSetup> DealSetups { get; set; }
        public virtual DbSet<DiscountSetup> DiscountSetups { get; set; }
        public virtual DbSet<EmployeeInformation> EmployeeInformations { get; set; }
        public virtual DbSet<ItemSetup> ItemSetups { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
    }
}
