//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBRPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSetup
    {
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Catagory_ID { get; set; }
        public string Brand_ID { get; set; }
        public Nullable<decimal> MinQuantity { get; set; }
        public Nullable<decimal> MaxQuantity { get; set; }
        public string ItemDesc { get; set; }
        public Nullable<int> IsActive { get; set; }
    }
}
