//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBRPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSetup
    {
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string CatagoryCode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string IsActive { get; set; }
        public string ItemDesc { get; set; }
    }
}
